<div class="flag-cards">

    <img src="<?php echo $block->getViewFileUrl('images/amex.png'); ?>" alt="amex">
    <img src="<?php echo $block->getViewFileUrl('images/simbolo_1.png'); ?>" alt="amex">
    <img src="<?php echo $block->getViewFileUrl('images/visa.png'); ?>" alt="amex">

    <img src="<?php echo $block->getViewFileUrl('images/hipercard.png'); ?>" alt="amex">
    <img src="<?php echo $block->getViewFileUrl('images/elo.png'); ?>" alt="amex">
    <img src="<?php echo $block->getViewFileUrl('images/simbolo_2.png'); ?>" alt="amex">

    <img src="<?php echo $block->getViewFileUrl('images/paypal.png'); ?>" alt="amex">
    <img src="<?php echo $block->getViewFileUrl('images/pix.png'); ?>" alt="amex">
    <img src="<?php echo $block->getViewFileUrl('images/boleto.png'); ?>" alt="amex">

</div>