<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis


/**
* Category view template
*
* @var $block \Magento\Framework\View\Element\Template
*/


?>

   <div class="promo-header-message">
       <?= __('Get %1 off your first order. Use coupon %2', '<strong style="background-color: #6220c1;">R$10,00</strong>', '<em>DESCONTO10</em>') ?>
   </div>
